export const japaneseThemes: string[] = [
  // Personal & Daily Life
  "A rainy day at home",
  "Moving to a new apartment",
  "My morning routine",
  "Cooking a new recipe",
  "A visit to the convenience store",
  "Spending a weekend alone",
  "Cleaning the room and finding something nostalgic",
  "Walking through the neighborhood",
  "A day without using a smartphone",
  "What I see from my window",
  "A small accident at home",
  "Taking care of a plant or pet",
  "When the power goes out",
  "Organizing my books",
  "A day without plans",
  "A lazy Sunday",
  "Having trouble sleeping",
  "Buying groceries for the week",
  "Listening to music while cleaning",
  "A day of heavy wind",
  "When I forgot my umbrella",
  "A peaceful evening",
  "Watching the sunset alone",
  "Losing something important",
  "Fixing something by myself",
  "Drinking tea and thinking",
  "Rearranging the furniture",
  "Finding an old diary",
  "Sitting on the balcony",
  "Making my lunch for the first time",

  // Relationships & Emotions
  "Missing someone far away",
  "Writing a letter to a friend",
  "Talking with my parents",
  "Remembering an argument",
  "Receiving a kind message",
  "Helping a friend in trouble",
  "Saying goodbye at the train station",
  "A childhood friend I lost contact with",
  "Meeting someone new",
  "Laughing with someone I love",
  "Feeling lonely in a crowd",
  "Talking late into the night",
  "Being misunderstood",
  "A secret I've never told anyone",
  "Seeing someone cry",
  "A difficult conversation",
  "A small act of kindness",
  "Feeling grateful",
  "Trusting someone again",
  "The moment I realized I'd changed",
  "Someone who inspires me",
  "A friend who moved away",
  "A visit to my grandparents",
  "A teacher I remember",
  "A sibling I look up to",
  "A misunderstanding that got resolved",
  "The first time I said “I'm sorry”",
  "When someone forgave me",
  "A compliment I'll never forget",
  "A smile that stayed with me",

  // Growth, Reflection & Change
  "Starting a new habit",
  "Facing a fear",
  "Learning something by failing",
  "A moment I was proud of",
  "Something I want to change",
  "A new experience that changed me",
  "Getting lost and learning from it",
  "Letting go of the past",
  "When I learned to be patient",
  "A dream I had and still remember",
  "What I learned this year",
  "A time I gave up too early",
  "What I'd say to my younger self",
  "Overcoming shyness",
  "Starting something late",
  "Finding my own pace",
  "Accepting things I can't control",
  "A promise I made to myself",
  "A moment I felt grown-up",
  "Learning to be alone",
  "My goal for the future",
  "Trying something I thought I couldn't do",
  "A time I almost gave up",
  "Discovering a new interest",
  "A mistake I made more than once",
  "A lesson I learned the hard way",
  "Realizing I was wrong",
  "Finding motivation again",
  "Taking a break and coming back",
  "A change I didn't expect",

  // Travel, Seasons & Environment
  "The first snowfall",
  "Visiting a hot spring",
  "Exploring a new town",
  "Getting lost in the city",
  "Watching the cherry blossoms",
  "Summer fireworks festival",
  "A night walk under the stars",
  "Traveling alone for the first time",
  "A train ride with strangers",
  "My favorite season",
  "The sound of cicadas",
  "Walking through fallen leaves",
  "A stormy night",
  "Watching the sea",
  "Climbing a small mountain",
  "Visiting a shrine or temple",
  "A long walk through the park",
  "Sleeping in a new place",
  "A surprising view from the window",
  "Hiking with a friend",
  "Watching the clouds pass",
  "Taking the wrong bus",
  "Seeing the ocean for the first time",
  "Waiting at an airport",
  "A sunrise I'll never forget",
  "Walking through snow",
  "Taking shelter from the rain",
  "Being stuck in traffic",
  "A hot summer afternoon",
  "A sudden change in the weather",

  // School, Work & Dreams
  "The first day of a new job",
  "Preparing for an exam",
  "Studying at a café",
  "A mistake I made at work",
  "Giving a presentation",
  "Getting feedback I didn't expect",
  "My dream job",
  "A difficult group project",
  "Meeting a mentor",
  "A class I really enjoyed",
  "A club I joined and left",
  "Skipping school for the first time",
  "My first part-time job",
  "An after-school memory",
  "Worrying about the future",
  "Trying to find balance",
  "Being late and feeling guilty",
  "Getting lost on the way to an interview",
  "A day I worked too much",
  "Starting something new at school",
  "Making a new friend at work",
  "A school event that went wrong",
  "Getting encouragement from someone",
  "A time I helped a classmate",
  "Writing my resume",
  "My dream when I was a child",
  "A teacher's advice I still remember",
  "Failing and trying again",
  "Learning something outside the classroom",
  "A place I want to work one day",
];

export function getRandomTheme(): string {
  const index = Math.floor(Math.random() * japaneseThemes.length);
  return japaneseThemes[index];
}
