import type { KanjiWatchListItem } from "../ui/KanjiWatchList";

export const demoKanjiWatchlist: KanjiWatchListItem[] = [
  {
    id: "1",
    kanji: "縁",
    word: "縁側",
    meaning: "veranda",
    retentionRate: 42,
    lastReviewed: "18 days ago",
    reviewCount: 14,
  },
  {
    id: "2",
    kanji: "携",
    word: "携わる",
    meaning: "to engage in",
    retentionRate: 48,
    lastReviewed: "26 days ago",
    reviewCount: 11,
  },
  {
    id: "3",
    kanji: "栽",
    word: "栽培",
    meaning: "cultivation",
    retentionRate: 51,
    lastReviewed: "31 days ago",
    reviewCount: 13,
  },
  {
    id: "4",
    kanji: "弊",
    word: "弊社",
    meaning: "our company",
    retentionRate: 54,
    lastReviewed: "24 days ago",
    reviewCount: 9,
  },
  {
    id: "5",
    kanji: "察",
    word: "察する",
    meaning: "to sense",
    retentionRate: 57,
    lastReviewed: "21 days ago",
    reviewCount: 12,
  },
  {
    id: "6",
    kanji: "充",
    word: "充実感",
    meaning: "sense of fulfillment",
    retentionRate: 59,
    lastReviewed: "15 days ago",
    reviewCount: 10,
  },
  {
    id: "7",
    kanji: "抜",
    word: "抜く",
    meaning: "to pull out",
    retentionRate: 61,
    lastReviewed: "19 days ago",
    reviewCount: 16,
  },
  {
    id: "8",
    kanji: "激",
    word: "激増",
    meaning: "sharp increase",
    retentionRate: 63,
    lastReviewed: "12 days ago",
    reviewCount: 8,
  },
  {
    id: "9",
    kanji: "貧",
    word: "貧しい",
    meaning: "poor",
    retentionRate: 65,
    lastReviewed: "9 days ago",
    reviewCount: 7,
  },
  {
    id: "10",
    kanji: "協",
    word: "協調",
    meaning: "cooperation",
    retentionRate: 67,
    lastReviewed: "14 days ago",
    reviewCount: 9,
  },
];
