name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - "server/**" # only run if files inside "server" folder changed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker credentials for GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker ${{ secrets.GAR_REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          IMAGE="${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/kanji-practice"
          docker build -f server/Dockerfile -t $IMAGE:latest server/
          docker push $IMAGE:latest
